println("BYVoid");
println(6 / 2 ++ "BYVoid" ++ 3 + 5);
println("http://" ++ "www." ++ ("byvoid" ++ ".com"));
println(expr(36, "+", 6));
a = [1, 2, 3];
println(a[0], a[1], a[2]);
println("Help\nNewLine!Backslash\\ Quote\" Slash/ Tab\t");
println(3 + "3");
println(3 + "3" ++ "2");
println(3 + ("3" ++ "2"));
println(("10" ++ a[0]) * 2);
println("BYVoid" == "BYVoid");
call("println", "Println Called");
cmd = "ec" ++ "ho";
call(cmd, "Echo Called");
//println([1, 2, 3]);
