echo("BYVoid");
echo(6 / 2 ++ "BYVoid" ++ 3 + 5);
echo("http://" ++ "www." ++ ("byvoid" ++ ".com"));
echo(expr(36, "+", 6));
a = [1, 2, 3];
echo(a[0], a[1], a[2]);
echo("Help\nNewLine!Backslash\\ Quote\" Slash/ Tab\t");
echo(3 + "3");
echo(3 + "3" ++ "2");
echo(3 + ("3" ++ "2"));
echo(("10" ++ a[0]) * 2);
echo("BYVoid" == "BYVoid");
//echo([1, 2, 3]);
